---
abstract: 'Validate Git Commit Messages'
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
build_requires:
  Test::More: 1.001002
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Git-Validate
requires:
  IPC::System::Simple: 1.25
  Module::Runtime: 0.013
  Moo: 1.003001
  namespace::clean: 0.23
resources:
  homepage: https://github.com/frioux/Git-Validate
  repository: https://github.com/frioux/Git-Validate.git
version: 0.001000
